apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-runner
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-runner
subjects:
  - kind: ServiceAccount
    name: flink-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink-runner